3.5 GPL commit

diff --git a/oam/install_scripts/infinidb b/oam/install_scripts/infinidb
--- a/oam/install_scripts/infinidb
+++ b/oam/install_scripts/infinidb
@@ -1,16 +1,17 @@
 #!/bin/bash
 #
-# $Id: infinidb 3704 2013-08-07 03:33:20Z bwilkinson $
+# $Id: infinidb.os 2937 2012-05-30 18:17:09Z rdempsey $
+#
 #
 # infinidb        Starts Calpont InfiniDB database platform
 #
 #
 # chkconfig: 2345 99 99
-# description: Calpont InfiniDB is a database platform that utilizes Mysql
+# description: InfiniDB is a database platform that utilizes Mysql
 #
 ### BEGIN INIT INFO
-# Provides:          infinidb
-# Required-Start:    $local_fs $remote_fs $network $syslog $all
+# Provides:          $infinidb
+# Required-Start:    $local_fs $remote_fs $network $syslog
 # Required-Stop:     $local_fs $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
@@ -20,7 +21,22 @@
 # Source function library.
 if [ -f /etc/init.d/functions ]; then
 	. /etc/init.d/functions
+else
+killproc() {
+	pkill $2 $1
+}
 fi
+
+unset pathmunge
+pathmunge () {
+	if ! echo $PATH | egrep -q "(^|:)$1($|:)" ; then
+	   if [ "$2" = "after" ] ; then
+	      PATH=$PATH:$1
+	   else
+	      PATH=$1:$PATH
+	   fi
+	fi
+}
 
 if [ -z "$INFINIDB_INSTALL_DIR" ]; then
 	test -f /etc/default/infinidb && . /etc/default/infinidb
@@ -30,151 +46,361 @@ if [ -z "$INFINIDB_INSTALL_DIR" ]; then
 	INFINIDB_INSTALL_DIR=/usr/local/Calpont
 fi
 
-export INFINIDB_INSTALL_DIR=$INFINIDB_INSTALL_DIR
+declare -x INFINIDB_INSTALL_DIR=$INFINIDB_INSTALL_DIR
 
-InstallDir=$INFINIDB_INSTALL_DIR
+CALPONT_HOME=$INFINIDB_INSTALL_DIR
+export CALPONT_CONFIG_FILE=$CALPONT_HOME/etc/Calpont.xml
+export CALPONT_LIB=$CALPONT_HOME/lib
 
-if [ $InstallDir != "/usr/local/Calpont" ]; then
-	export PATH=$InstallDir/bin:$InstallDir/mysql/bin:/bin:/usr/bin
-	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$InstallDir/lib:$InstallDir/mysql/lib/mysql
-fi
+pathmunge $CALPONT_HOME/bin
 
-#hadoop
-plugin=`$INFINIDB_INSTALL_DIR/bin/getConfig SystemConfig DataFilePlugin`
-if [ -n "$plugin" ]; then
-	setenv=`$InstallDir/bin/getConfig SystemConfig DataFileEnvFile`
-	. $InstallDir/bin/$setenv >/dev/null 2>&1
-fi
+RETVAL=0
 
-if [ -e $InstallDir/lib/libjemalloc.so ]; then
-	export LD_PRELOAD=$InstallDir/lib/libjemalloc.so
-elif [ -e $InstallDir/lib/libjemalloc.so.1 ]; then
-	export LD_PRELOAD=$InstallDir/lib/libjemalloc.so.1
-fi
+# run dbbuilder if necessary
+checkForSysCat() {
+	if [ `editem -o 1001 | wc -l` -eq 0 ]; then
 
-test -f $InstallDir/post/functions && . $InstallDir/post/functions
+		echo -n "creating system catalog (be patient): "
+		dbbuilder 7 > /tmp/dbbuilder.log &
 
-mt=`module_type`
-mid=`module_id`
+		while [ -d /proc/$! ]; do
+			sleep 5
+			echo -n "."
+		done
 
-has_um=`$InstallDir/bin/getConfig SystemModuleConfig ModuleCount2`
-if [ "x$has_um" = x ]; then
-	has_um=0
-fi
-
-user=$USER
-if [ -z "$user" ]; then
-        user=root
-fi
-
-checkInstallSetup() {
-	InitialInstallFlag=`$InstallDir/bin/getConfig -c $InstallDir/etc/Calpont.xml Installation InitialInstallFlag`
-	if [ $InitialInstallFlag != "y" ]; then
-		echo "Please run the postConfigure install script, check the Installation Guide"
-		echo "for additional details"
-		rm -f /var/lock/subsys/infinidb
-		exit 1
+		echo " done."
 	fi
 }
 
-[ -f $InstallDir/bin/ProcMon ] || exit 0
+# run upgrade script
+upgradeDB() {
 
-start() {
-	if [ -f /var/lock/subsys/infinidb ]; then
-		echo "InfiniDB Database Platform already running"
-		exit 0
+ 	echo "Validate InfiniDB System Catalog:"
+
+	df=$CALPONT_HOME/mysql/my.cnf
+
+	#check for password set
+	pwprompt=" "
+	password=" "
+	userprompt=" *** Enter MySQL password: "
+	while true ; do
+		$CALPONT_HOME/mysql/bin/mysql --defaults-file=$df --force --user=root $pwprompt -e status &>/tmp/idbmysql.log
+		
+		egrep -qs "ERROR 1045" /tmp/idbmysql.log
+		if [ $? -eq 0 ]; then
+			echo ""
+			stty_orig=`stty -g`
+			stty -echo
+			echo -n "$userprompt"
+			read -t 30 password
+			stty $stty_orig
+			echo " "
+
+			if [ -z $password ]; then
+				echo " "
+				echo " Timeout: Continuing"
+				return
+			else
+				pwprompt="--password=$password"
+				userprompt=" *** Incorrect password, please re-enter MySQL password: "
+			fi
+		else
+			egrep -qs "InfiniDB" /tmp/idbmysql.log
+			if [ $? -ne 0 ]; then
+				echo ""
+				echo " ERROR: MySQL runtime error, exit..."
+				cat /tmp/idbmysql.log
+				exit 1
+			else
+				rm -f /tmp/idbmysql.log
+				break
+			fi
+		fi
+	done
+
+	status="ERROR"
+	if [ -x $CALPONT_HOME/bin/upgrade-infinidb.sh ]; then
+		status="`$CALPONT_HOME/bin/upgrade-infinidb.sh doupgrade --password=$password`"
+	fi
+	if [ "$status" != "OK" ]; then
+		echo " ERROR: Database upgrade script failed"
+		exit 1
+      fi
+
+	echo " Validation Succesfully Completed"
+
+}
+
+
+# functionality test
+funTest() {
+	#check logging functionality
+	echo -n " InfiniDB Logging check: " 
+	logger -p local1.debug "Functional Test"
+	status=`grep -s "Functional Test" /var/log/Calpont/debug.log > /tmp/debug.check`
+	if [ `cat /tmp/debug.check | wc -c` -eq 0 ]; then
+		echo "ERROR: InfiniDB logging not functioning"
+	else
+		echo "DONE"
 	fi
 
-	(mkdir -p /var/lock/subsys && touch /var/lock/subsys/infinidb) >/dev/null 2>&1
+	#check stop process flag
+	echo -n " Platform Process check: " 
 
-	if [ -x $InstallDir/bin/infinidb.pre-start ]; then
-		$InstallDir/bin/infinidb.pre-start
-		if [ $? -ne 0 ]; then
-			echo "Error running InfiniDB pre-start script, not starting InfiniDB"
-			rm -f /var/lock/subsys/infinidb
+	if [ -f /tmp/StopCalpont ]; then
+		echo "InfiniDB Platform is down"
+		return
+	fi
+
+	#check Process statility from logs and ps command
+	PSCOUNT=1
+
+	DMLProcCnt=`ps ax -opid,comm | grep -c DMLProc | awk '{print $1}'`
+	DDLProcCnt=`ps ax -opid,comm | grep -c DDLProc | awk '{print $1}'`
+	ExeMgrCnt=`ps ax -opid,comm | grep -c ExeMgr | awk '{print $1}'`
+	PrimProcCnt=`ps ax -opid,comm | grep -c PrimProc | awk '{print $1}'`
+	controllernodeCnt=`ps ax -opid,comm | grep -c controllernode | awk '{print $1}'`
+	workernodeCnt=`ps ax -opid,comm | grep -c workernode | awk '{print $1}'`
+
+	badProc="dummy"
+	if [ $DMLProcCnt -ne $PSCOUNT ]; then
+		badProc="DMLProc"
+	elif [ $DDLProcCnt -ne $PSCOUNT ]; then
+		badProc="DDLProc"
+	elif [ $ExeMgrCnt -ne $PSCOUNT ]; then
+		badProc="ExeMgr"
+	elif [ $PrimProcCnt -ne $PSCOUNT ]; then
+		badProc="PrimProc"
+	elif [ $controllernodeCnt -ne $PSCOUNT ]; then
+		badProc="controllernode"
+	elif [ $workernodeCnt -ne $PSCOUNT ]; then
+		badProc="workernode"
+	fi
+
+	if [ $badProc != "dummy" ]; then
+		echo " ERROR: Problem with InfiniDB process $badProc, should be a single version running"
+		echo " "
+		echo "***Stopping InfiniDB to allow the process problem to be resolved."
+		echo " "
+		stop
+		exit 1
+	fi
+
+	DMLProcPID1=`ps ax -opid,comm | grep DMLProc | awk '{print $1}'`
+	DDLProcPID1=`ps ax -opid,comm | grep DDLProc | awk '{print $1}'`
+	ExeMgrPID1=`ps ax -opid,comm | grep ExeMgr | awk '{print $1}'`
+	PrimProcPID1=`ps ax -opid,comm | grep PrimProc | awk '{print $1}'`
+	controllernodePID1=`ps ax -opid,comm | grep controllernode | awk '{print $1}'`
+	workernodePID1=`ps ax -opid,comm | grep workernode | awk '{print $1}'`
+
+	sleep 3
+	DMLProcPID2=`ps ax -opid,comm | grep DMLProc | awk '{print $1}'`
+	DDLProcPID2=`ps ax -opid,comm | grep DDLProc | awk '{print $1}'`
+	ExeMgrPID2=`ps ax -opid,comm | grep ExeMgr | awk '{print $1}'`
+	PrimProcPID2=`ps ax -opid,comm | grep PrimProc | awk '{print $1}'`
+	controllernodePID2=`ps ax -opid,comm | grep controllernode | awk '{print $1}'`
+	workernodePID2=`ps ax -opid,comm | grep workernode | awk '{print $1}'`
+
+	badProc="dummy"
+	if [ $DMLProcPID1 -ne $DMLProcPID2 ]; then
+		badProc="DMLProc"
+	elif [ $DDLProcPID1 -ne $DDLProcPID2 ]; then
+		badProc="DDLProc"
+	elif [ $ExeMgrPID1 -ne $ExeMgrPID2 ]; then
+		badProc="ExeMgr"
+	elif [ $PrimProcPID1 -ne $PrimProcPID2 ]; then
+		badProc="PrimProc"
+	elif [ $controllernodePID1 -ne $controllernodePID2 ]; then
+		badProc="controllernode"
+	elif [ $workernodePID1 -ne $workernodePID2 ]; then
+		badProc="workernode"
+	fi
+
+	if [ $badProc != "dummy" ]; then
+		echo " ERROR: $badProc not Active"
+
+		status=`tail -1 /var/log/Calpont/crit.log | grep  "allocated too much memory" > /tmp/crit.check`
+		if [ `cat /tmp/crit.check | wc -c` -ne 0 ]; then
+			echo " There isn't enough available system memory for the InfiniDB Process."
+			echo " Check available/active memory and settings of /etc/sysctl.conf for memory limitations."
+			echo " Check /var/log/Calpont/*.log files for additional information."
+			echo " "
+			echo "***Stopping InfiniDB to allow the memory problem to be resolved."
+			echo " "
+			stop
+			exit 1
+		else
+			echo " Check /var/log/Calpont/*.log files for additional information"
+			echo " "
+			echo "***Stopping InfiniDB to allow the process problem to be resolved."
+			echo " "
+			stop
 			exit 1
 		fi
+	else
+		echo "DONE"
 	fi
-	checkInstallSetup
 
-	CoreFileFlag=`$InstallDir/bin/getConfig -c $InstallDir/etc/Calpont.xml Installation CoreFileFlag`
-	if [ $CoreFileFlag = "y" ]; then
-		SUDO=
-		if [ -z "$NO_NONROOT_SUDO" -a "$user" != "root" ]; then 
-			SUDO="sudo"
+	echo -n " MySQL Daemon check: "
+	test -x /etc/init.d/mysql-Calpont && /etc/init.d/mysql-Calpont status
+
+	#check dbrm
+	echo -n " Database check: "
+
+	$CALPONT_HOME/bin/dbrmctl status > /tmp/dbrmctl.status
+	status=`cat /tmp/dbrmctl.status | awk '{print $1}'`
+	if [ $status != "OK." ]; then
+		echo -n "ERROR: "
+		cat /tmp/dbrmctl.status
+		if [ $status != "DBRM is currently Read Only!" ]; then
+			echo " ***DDL/DML are disabled, can only perform queries"
 		fi
-
-		#infinidb core files
-		$SUDO ulimit -c unlimited  > /dev/null 2>&1
-		$SUDO sysctl -q -w kernel.core_uses_pid=1  > /dev/null 2>&1
-		$SUDO sysctl -q -w kernel.core_pattern=/var/log/Calpont/corefiles/core.%e.%p  > /dev/null 2>&1
+		echo " Check /var/log/Calpont/*.log files for additional information"
+		return
 	fi
 
-	RETVAL=0
-	echo "Starting InfiniDB Database Platform"
-	rm -f /tmp/StopCalpont
-	exec $InstallDir/bin/run.sh $InstallDir/bin/ProcMon  > /dev/null 2>&1 &
+	$CALPONT_HOME/bin/editem -o 2001 > /tmp/editem.status 2>&1
+	cnt=`cat /tmp/editem.status | wc -l`
+	if [ $cnt -eq 0 ]; then
+		echo "ERROR: NO system catalog data"
+		echo " Check /var/log/Calpont/*.log files for additional information"
+		echo " "
+		echo "***Stopping InfiniDB to allow the problem to be resolved."
+		echo "A clean re-install of InfiniDB might be required to correct."
+		stop
+		exit 1
+	fi
 
+	#run save_brm to get a current file and run post-test
+	$CALPONT_HOME/bin/save_brm > /tmp/savebrm.status 2>&1
+	$CALPONT_HOME/bin/startupTests.sh > /tmp/startupTests.status 2>&1
+	status=`cat /tmp/startupTests.status | awk '{print $1}'`
+	if [ x$status != "xOK" ]; then
+		echo "ERROR: Check /var/log/Calpont/crit.log files for additional information"
+		echo " "
+		echo "***Stopping InfiniDB to allow the problem to be resolved."
+		stop
+		exit 1
+	fi
+
+	echo "DONE"
+}
+
+checkInstallSetup() {
+	if [ ! -d $CALPONT_HOME/data1/systemFiles/dbrm ]; then
+		install-infinidb.sh
+	fi
+}
+
+killProcesses() {
+	killproc DMLProc -9 > /dev/null
+	killproc DDLProc -9 > /dev/null
+	killproc ExeMgr -9 > /dev/null
+	killproc WriteEngineServer -9 > /dev/null
+	# only first 15 chars can be used on debian
+	killproc WriteEngineServ -9 > /dev/null
+	killproc PrimProc -9 > /dev/null
+	killproc controllernode -9 > /dev/null
+	killproc workernode -9 > /dev/null
+}
+
+start() {
+	checkInstallSetup
+	touch /tmp/StopCalpont
+	killProcesses
+ 	echo -n "Starting Calpont InfiniDB Database Platform: "
+	rm -f /tmp/StopCalpont
+	brm_prefix=$(cat $(getConfig SystemConfig DBRMRoot)_current 2>/dev/null)
+	if [ -n "$brm_prefix" ]; then
+		echo -n "."
+		load_brm $brm_prefix > /tmp/load_brm.log
+		sleep 5
+		grep OK /tmp/load_brm.log >/dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			echo " "
+			echo "Error when loading BRM data. Check log file at /tmp/load_brm.log"
+			return  1
+		fi
+	fi
+	echo -n "."
+	run.sh workernode DBRM_Worker1 fg >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh controllernode fg >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh PrimProc >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh WriteEngineServer >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh ExeMgr >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh DDLProc >/dev/null 2>&1 &
+	sleep 1
+	echo -n "."
+	run.sh DMLProc >/dev/null 2>&1 &
+	sleep 5
+	echo " DONE"
+	checkForSysCat
+	RETVAL=0
+ 	echo "Starting Calpont InfiniDB MySQL: "
+	test -x /etc/init.d/mysql-Calpont && /etc/init.d/mysql-Calpont start
+	sleep 2
+	upgradeDB
+	[ $RETVAL -eq 0 ] && [ -d /var/lock/subsys ] && touch /var/lock/subsys/infinidb
+	echo "Perform Functionality test: "
+	funTest
 	return $RETVAL
 }	
 stop() {
-	echo "Shutting down InfiniDB Database Platform"
+ 	echo "Shutting down Calpont InfiniDB MySQL: "
 	touch /tmp/StopCalpont
-	pkill -9 ProcMon
-	pkill -9 ProcMgr
-	pkill -9 snmptrapd
+	test -x /etc/init.d/mysql-Calpont && /etc/init.d/mysql-Calpont stop
+	echo "Shutting down Calpont InfiniDB Database Platform: "
+	killProcesses
+	reset_locks > /dev/null 2>&1
+	save_brm > /dev/null 2>&1
 	sleep 1
-	$InstallDir/bin/clearShm
-	RETVAL=$?
-	rm -f /var/lock/subsys/infinidb
+	RETVAL=0
+	echo
 	fuser -k 8604/tcp > /dev/null 2>&1
-	test -f $InstallDir/mysql/mysql-Calpont || return $RETVAL
-	$InstallDir/mysql/mysql-Calpont stop > /dev/null 2>&1
-	if [ -x $InstallDir/bin/infinidb.post-stop ]; then
-		$InstallDir/bin/infinidb.post-stop
-	fi
+	clearShm
+	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/infinidb
 	return $RETVAL
 }
 restart() {
 	stop
+	sleep 10
 	start
-}
+}	
+
 status() {
-	isrunning=0
-	if [ $EUID -eq 0 ]; then
-		if [ -f /var/lock/subsys/infinidb ]; then
-			isrunning=1
-		fi
-	else
-		pgrep ProcMon >/dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			isrunning=1
-		fi
-	fi
-	if [ $isrunning -ne 0 ]; then
-		echo "InfiniDB is running"
-	else
-		echo "InfiniDB is not running"
-	fi
-}
+	RETVAL=0
+	funTest
+	return $RETVAL
+}	
+
 
 case "$1" in
-start)
-	start
+  start)
+  	start
 	;;
-stop)
-	stop
+  stop)
+  	stop
 	;;
-restart)
-	restart
+  restart)
+  	restart
 	;;
-condrestart)
-	[ -f /var/lock/subsys/infinidb ] && restart || :
+  condrestart)
+  	[ -f /var/lock/subsys/infinidb ] && restart || :
 	;;
-status)
-	status
+  status)
+  	status
 	;;
-*)
+  *)
 	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
 	exit 1
 esac
diff --git a/oam/install_scripts/post-install b/oam/install_scripts/post-install
--- a/oam/install_scripts/post-install
+++ b/oam/install_scripts/post-install
@@ -1,49 +1,21 @@
 #!/bin/bash
 #
-# $Id: post-install 3705 2013-08-07 19:47:20Z dhill $
+# $Id: post-install 1886 2010-04-01 18:30:38Z dhill $
 #
 # Post-install steps for calpont install
 
 prefix=/usr/local
-installdir=$prefix/Calpont
 rpmmode=install
-user=$USER
-if [ -z "$user" ]; then
-	user=root
-fi
-quiet=0
 
 for arg in "$@"; do
 	if [ `expr -- "$arg" : '--prefix='` -eq 9 ]; then
 		prefix="`echo $arg | awk -F= '{print $2}'`"
-		installdir=$prefix/Calpont
 	elif [ `expr -- "$arg" : '--rpmmode='` -eq 10 ]; then
 		rpmmode="`echo $arg | awk -F= '{print $2}'`"
-	elif [ `expr -- "$arg" : '--installdir='` -eq 13 ]; then
-		installdir="`echo $arg | awk -F= '{print $2}'`"
-		prefix=`dirname $installdir`
-	elif [ `expr -- "$arg" : '--user='` -eq 7 ]; then
-		user="`echo $arg | awk -F= '{print $2}'`"
-	elif [ `expr -- "$arg" : '--quiet'` -eq 7 ]; then
-		quiet=1
-	elif [ `expr -- "$arg" : '--plugin='` -eq 9 ]; then
-		plugin="`echo $arg | awk -F= '{print $2}'`"
 	else
-		echo "post-install: ignoring unknown argument: $arg" 1>&2
+		echo "ignoring unknown argument: $arg" 1>&2
 	fi
 done
-
-#remove ending '/'
-case "$installdir" in
-*/)
-	installdir=${installdir%/*}
-	;;
-esac
-
-if [ $installdir != "/usr/local/Calpont" ]; then
-	export INFINIDB_INSTALL_DIR=$installdir
-	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib
-fi
 
 #check 64-bit OS compatiable
 arch=`uname -m`
@@ -53,309 +25,82 @@ if [ $patcnt -ne 0 ]; then
 	is64bitos=0
 fi
 is64bitpkg=1
-file $installdir/bin/PrimProc | grep '64-bit' >/dev/null 2>&1
+file ${prefix}/Calpont/bin/PrimProc | grep '64-bit' >/dev/null 2>&1
 if [ $? -ne 0 ]; then
 	is64bitpkg=0
 fi
 if [ $is64bitpkg -eq 1 -a $is64bitos -ne 1 ]; then
-	echo "ERROR: Incompatiable Version, package is intended for a x86_64 architecture"
+	echo "ERROR: Incompatible version, package is intended for a x86_64 architecture"
 	echo "exiting...."
 	exit 1
 fi
 
-if [ ! -f $installdir/etc/Calpont.xml ]; then
-	echo "$installdir/etc/Calpont.xml not found, exiting"
+if [ ! -f ${prefix}/Calpont/etc/Calpont.xml ]; then
+	echo "${prefix}/Calpont/etc/Calpont.xml not found, exiting"
 	exit 1
 fi
 
-cd $installdir/lib || exit 1
+cd ${prefix}/Calpont/lib || exit 1
 for lib in *.so.1.0.0; do
 	blib=`basename $lib .1.0.0`
 	ln -sf $lib $blib
+	ln -sf $lib $blib.1
 done
-chown -h $user.$user *.so >/dev/null 2>&1
+chown -h root.root *.so
 if [ -f libnetsnmp.so.5.2.1 ]; then
 	for lib in *.so.5.2.1; do
 		blib=`basename $lib .5.2.1`
 		ln -sf $lib $blib
 		ln -sf $lib ${blib}.5
 	done
-	chown -h $user.$user *.so *.so.5 >/dev/null 2>&1
+	chown -h root.root *.so *.so.5
 fi
-if [ -f libstdc++.so.6.0.14 ]; then
-	ln -sf libstdc++.so.6.0.14 libstdc++.so.6
-	chown -h $user.$user libstdc++.so.6 >/dev/null 2>&1
-fi
-
-ln -sf libjemalloc.so.3.3.0 libjemalloc.so
-chown -h $user.$user libjemalloc.so >/dev/null 2>&1
-
-# TODO-based on early experience with HDP it doesn't install bigtop
-# so the code below will not correctly detect JAVA_HOME.  Need to 
-# decide how to handle
-# Autodetect JAVA_HOME if not defined
-#if [ -e /usr/libexec/bigtop-detect-javahome ]; then
-#. /usr/libexec/bigtop-detect-javahome
-#elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
-#. /usr/lib/bigtop-utils/bigtop-detect-javahome
-#fi
-#ln -sf $JAVA_HOME/jre/lib/amd64/server/libjvm.so
-#chown -h $user.$user libjvm.so >/dev/null 2>&1
 
 cd /
-
-test -d /var/log/Calpont || mkdir /var/log/Calpont >/dev/null 2>&1
-test -d /var/log/Calpont/archive || mkdir /var/log/Calpont/archive >/dev/null 2>&1
-test -d /var/log/Calpont/corefiles || mkdir /var/log/Calpont/corefiles >/dev/null 2>&1
-test -d /var/log/Calpont/trace || mkdir /var/log/Calpont/trace >/dev/null 2>&1
+test -d /var/log/Calpont || mkdir /var/log/Calpont
+test -d /var/log/Calpont/archive || mkdir /var/log/Calpont/archive
+test -d /var/log/Calpont/corefiles || mkdir /var/log/Calpont/corefiles
+test -d /var/log/Calpont/trace || mkdir /var/log/Calpont/trace
 # make sure trace dir is world-writable and sticky
-chmod 1777 /var/log/Calpont/trace >/dev/null 2>&1
-test -d $installdir/data || mkdir $installdir/data
-test -d $installdir/data1 || mkdir $installdir/data1
-test -d $installdir/data1/systemFiles || mkdir $installdir/data1/systemFiles
-test -d $installdir/data1/systemFiles/dbrm || mkdir $installdir/data1/systemFiles/dbrm
-test -d $installdir/data1/systemFiles/dataTransaction || mkdir $installdir/data1/systemFiles/dataTransaction
-test -d $installdir/data1/systemFiles/dataTransaction/archive || mkdir $installdir/data1/systemFiles/dataTransaction/archive
-chmod 1777 $installdir/data1 >/dev/null 2>&1
-chmod -R 1777 $installdir/data1/systemFiles >/dev/null 2>&1
-chmod 1777 $installdir/etc > /dev/null 2>&1
-test -d /var/log/Calpont/data || ln -sf $installdir/data1/systemFiles/dataTransaction /var/log/Calpont/data > /dev/null 2>&1
-
-#create the bulk-load dirs
-mkdir -p $installdir/data/bulk/data/import >/dev/null 2>&1
-mkdir -p $installdir/data/bulk/log >/dev/null 2>&1
-mkdir -p $installdir/data/bulk/job >/dev/null 2>&1
-mkdir -p $installdir/data/bulk/rollback >/dev/null 2>&1
-mkdir -p $installdir/data/bulk/tmpjob >/dev/null 2>&1
-rm -f $installdir/data/bulk/tmpjob/* >/dev/null 2>&1
+chmod 1777 /var/log/Calpont/trace
+test -d ${prefix}/Calpont/data || mkdir ${prefix}/Calpont/data
+test -d ${prefix}/Calpont/data1 || mkdir ${prefix}/Calpont/data1
+test -d ${prefix}/Calpont/data1/systemFiles || mkdir ${prefix}/Calpont/data1/systemFiles
+test -d ${prefix}/Calpont/data1/systemFiles/dataTransaction || mkdir ${prefix}/Calpont/data1/systemFiles/dataTransaction
+test -d ${prefix}/Calpont/data1/systemFiles/dataTransaction/archive || mkdir ${prefix}/Calpont/data1/systemFiles/dataTransaction/archive
+test -d ${prefix}/Calpont/data1/systemFiles/dbrm || mkdir ${prefix}/Calpont/data1/systemFiles/dbrm
+chmod -R 1777 ${prefix}/Calpont/data1/systemFiles/dbrm > /dev/null 2>&1
+chmod -R 1777 ${prefix}/Calpont/data1 > /dev/null 2>&1
+chmod -R 1777 ${prefix}/Calpont/etc > /dev/null 2>&1
+test -d /var/log/Calpont/data || ln -sf ${prefix}/Calpont/data1/systemFiles/dataTransaction /var/log/Calpont/data
 
 #create infinidb temp file directory
-mkdir -p /tmp/infinidb_tmp_files >/dev/null 2>&1
+mkdir -p /tmp/infinidb_tmp_files
+
+#create the bulk-load dirs
+mkdir -p ${prefix}/Calpont/data/bulk/data/import >/dev/null 2>&1
+mkdir -p ${prefix}/Calpont/data/bulk/log >/dev/null 2>&1
+mkdir -p ${prefix}/Calpont/data/bulk/job >/dev/null 2>&1
+mkdir -p ${prefix}/Calpont/data/bulk/rollback >/dev/null 2>&1
+mkdir -p ${prefix}/Calpont/data/bulk/tmpjob >/dev/null 2>&1
+rm -f ${prefix}/Calpont/data/bulk/tmpjob/* >/dev/null 2>&1
 
 #setup core file directory and link
 mkdir /var/log/Calpont/corefiles > /dev/null 2>&1
-chmod 777 /var/log/Calpont/corefiles > /dev/null 2>&1
+chmod 777 /var/log/Calpont/corefiles 
 
 #create mount directories
 mkdir /mnt/tmp > /dev/null 2>&1
 mkdir /var/log/Calpont/data/archive > /dev/null 2>&1
 
-#remove this fstab back file if its left over from 2.x version
-if test -f /etc/fstab.calpontSave ; then
-	rm -f /etc/fstab.calpontSave > /dev/null 2>&1
-fi
-
-
 # install Calpont Log Rotate File
-test -d $installdir/mysql/db || mkdir -p $installdir/mysql/db
-cp $installdir/bin/calpontLogRotate /etc/logrotate.d/calpont > /dev/null 2>&1
-rm -rf $installdir/mysql/db/infinidb_log_archive > /dev/null 2>&1
-
-# delete Calpont shared memory segments
-$installdir/bin/Calpont/bin/clearShm  > /dev/null 2>&1
-
-#setup the infinidb service script
-rm -f /etc/init.d/infinidb >/dev/null 2>&1
-cp $installdir/bin/infinidb /etc/init.d >/dev/null 2>&1
-if [ -x /sbin/chkconfig ]; then
-	/sbin/chkconfig --add infinidb > /dev/null 2>&1
-	/sbin/chkconfig infinidb on > /dev/null 2>&1
-elif [ -x /usr/sbin/update-rc.d ]; then
-	/usr/sbin/update-rc.d infinidb defaults 99 > /dev/null 2>&1
-else
-	echo ""
-	echo "Package 'chkconfig' or 'update-rc.d' not installed, contact your sysadmin if you want to setup to autostart for infinidb"	
-fi
-
-#setup InfiniDB system logging
-if [ $user = "root" ]; then
-	$installdir/bin/syslogSetup.sh install > /tmp/syslog_install.log 2>&1
-	chmod 777 /dev/shm
-elif [ -z "$NO_NONROOT_SUDO" ]; then
-	sudo $installdir/bin/syslogSetup.sh --installdir=$installdir install > /tmp/syslog_install.log 2>&1
-	sudo chown $user:$user $installdir/etc/Calpont.xml
-	sudo chmod 777 /var/log
-	sudo chmod -R 777 /var/log/Calpont
-	sudo chmod 777 /dev/shm
-	sudo rm -f /var/lock/subsys/mysql-Calpont
-	sudo rm -f /tmp/StopCalpont
-
-	sed -i -e s@/usr/local/Calpont@$installdir@g $installdir/bin/infinidb.def
-	sudo cp $installdir/bin/infinidb.def /etc/default/infinidb
-fi
-
-#check if InfiniDB system logging was setup
-cat /tmp/syslog_install.log | grep 'No System Logging' >/dev/null 2>&1
-if [ $? -eq 0 ]; then
-	cat /tmp/syslog_install.log
-fi
-
-#setup alias commands
-eval userhome=~$user
-bashFile=$userhome/.bashrc
-touch ${bashFile}
-if [ $installdir != "/usr/local/Calpont" ]; then
-	sed -i -e s@/usr/local/Calpont@$installdir@g $installdir/bin/calpontAlias
-fi
-egrep -qs 'Calpont Database Platform Alias Commands' ${bashFile}
-rc1=$?
-egrep -qs 'InfiniDB Alias Commands' ${bashFile}
-rc2=$?
-if [ $rc1 -ne 0 -a $rc2 -ne 0 ]; then
-	rm -f ${bashFile}.calpontSave
-	cp ${bashFile} ${bashFile}.calpontSave >/dev/null 2>&1
-	cat $installdir/bin/calpontAlias >> ${bashFile}
-	echo " " >> ${bashFile}
-fi
-
-#check and get amazon EC2 env variables
-if [ -n "$EC2_HOME" ]; then
-	$installdir/bin/setConfig -d Installation EC2_HOME $EC2_HOME >/dev/null 2>&1
-
-	if [ -n "$EC2_HOME" ]; then
-		$installdir/bin/setConfig -d Installation JAVA_HOME $JAVA_HOME >/dev/null 2>&1
-	fi
-
-	$installdir/bin/setConfig -d Installation EC2_PATH $PATH:/home/ec2/bin:/opt/aws/bin >/dev/null 2>&1
-fi
+cp ${prefix}/Calpont/bin/calpontLogRotate /etc/logrotate.d/calpont > /dev/null 2>&1
+cp ${prefix}/Calpont/bin/transactionLog /etc/cron.d/.
+chmod 644 /etc/cron.d/transactionLog
 
 #log install message
-test -f $installdir/post/functions && . $installdir/post/functions
-LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib $installdir/bin/cplogger -i 19 "***** InfiniDB Installed *****"
-
-#setup hadoop
-hadoop=`which hadoop 2>/dev/null`
-if [ -z $hadoop ]; then
-	#not hadoop - check for non-root user
-	if [ $installdir != "/usr/local/Calpont" -a $quiet -eq 0 ]; then
-cat <<EOD
-The next steps are:
-
-export INFINIDB_INSTALL_DIR=$installdir
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib:$installdir/mysql/lib/mysql
-$installdir/bin/postConfigure -i $installdir
-
-EOD
-	else
-cat <<EOD
-The next step is:
-
-$installdir/bin/postConfigure
-
-EOD
-	fi
-        exit 0
-else
-	#hadoop install
-	chmod 777 $installdir/bin/setenv-hdfs-12
-	chmod 777 $installdir/bin/setenv-hdfs-20
-
-	DATAPLUGIN=`$installdir/bin/getConfig SystemConfig DataFilePlugin`
-	DATAENV=`$installdir/bin/getConfig SystemConfig DataFileEnvFile`
-
-	PASS=true
-	if [ $DATAENV != "unassigned" ]; then
-		. $installdir/bin/$DATAENV
-		$installdir/bin/hdfsCheck $DATAPLUGIN > /tmp/hdfs-config-test.log 2>&1
-		if [ $? -ne 0 ]; then
-			PASS=false
-		fi
-	else
-		PASS=false
-	fi
-
-	if [ !PASS ]; then
-		#Failed, see what passes
-		. $installdir/bin/setenv-hdfs-20
-		$installdir/bin/hdfsCheck $installdir/lib/hdfs-20.so > /tmp/hdfs-20-test.log 2>&1
-		if [ $? -eq 0 ]; then
-			#Passed, save
-			DATAPLUGIN=$installdir/lib/hdfs-20.so
-			DATAENV=setenv-hdfs-20
-		else
-			. $installdir/bin/setenv-hdfs-12
-			$installdir/bin/hdfsCheck $installdir/lib/hdfs-12.so > /tmp/hdfs-12-test.log 2>&1
-			if [ $? -eq 0 ]; then
-				#Passed, save
-				DATAPLUGIN=$installdir/lib/hdfs-12.so
-				DATAENV=setenv-hdfs-12
-			else
-				DATAPLUGIN="unassigned"
-				DATAENV="unassigned"
-			fi
-		fi
-
-		#set in config file
-		$installdir/bin/setConfig -d SystemConfig DataFilePlugin $DATAPLUGIN >/dev/null 2>&1
-		$installdir/bin/setConfig -d SystemConfig DataFileEnvFile $DATAENV >/dev/null 2>&1
-
-		#hadoop test error
-		if [ $DATAENV == "unassigned" ]; then
-			#check for non-root user
-			if [ $installdir != "/usr/local/Calpont" -a $quiet -eq 0 ]; then
-cat <<EOD
-
-If you are intending to install InfiniDB over Hadoop, the Hadoop sanity check did not pass.  
-Check the hdfs logs in /tmp for additional information and make sure the HDFS services is running
-Please Contact InfiniDB Customer Support for addition support.
-
-If you are intending to install InfiniDB without Hadoop, the next steps are:
-
-export INFINIDB_INSTALL_DIR=$installdir
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib:$installdir/mysql/lib/mysql
-$installdir/bin/postConfigure -i $installdir
-
-EOD
-			else
-cat <<EOD
-
-If you are intending to install InfiniDB over Hadoop, the Hadoop sanity check did not pass.  
-Check the hdfs logs in /tmp for additional information and make sure the HDFS services is running
-Please Contact InfiniDB Customer Support for addition support.
-
-If you are intending to install InfiniDB without Hadoop, the next steps are:
-
-$installdir/bin/postConfigure
-
-EOD
-			fi
-		else
-			#hadoop test passed, check for non-root user
-			if [ $installdir != "/usr/local/Calpont" -a $quiet -eq 0 ]; then
-cat <<EOD
-
-If you are intending to install InfiniDB over Hadoop, the next steps are:
-
-export INFINIDB_INSTALL_DIR=$installdir
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib:$installdir/mysql/lib/mysql
-
-. $installdir/bin/$DATAENV
-$installdir/bin/postConfigure -i $installdir
-
-If you are intending to install InfiniDB without Hadoop, the next steps are:
-
-export INFINIDB_INSTALL_DIR=$installdir
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/lib:$installdir/mysql/lib/mysql
-$installdir/bin/postConfigure -i $installdir
-
-EOD
-			else
-cat <<EOD
-
-If you are intending to install InfiniDB over Hadoop, the next steps are:
-
-. $installdir/bin/$DATAENV
-$installdir/bin/postConfigure
-
-If you are intending to install InfiniDB without Hadoop, the next step is:
-
-$installdir/bin/postConfigure
-
-EOD
-			fi
-		fi
-	fi
-fi
+test -f /usr/local/Calpont/post/functions && . /usr/local/Calpont/post/functions
+cplogger -i 100 "***** InfiniDB Installed *****"
 
 exit 0
 
